### ISSUE TITLE
Black screen on the local side with 4G on Android

### ISSUE THREAD

**Issue by georgemichailou** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#8]
I use Xamarin.Agora.Full.Forms 2.9.4 version but when i try to join without Wi-FI, my view is black and if someone joins to my channel doesn't see or hear anything.

When i enable the Wi-Fi is working perfect.

```
        public void Init()
        {
            _isEnded = false;
            if (_agoraService == null)
            {
                _agoraService = AgoraService.Current;
                _agoraService.JoinChannelSuccess += _agoraService_JoinChannelSuccess;
                _agoraService.OnDisconnected += OnDisconnected;
                _agoraService.OnNewStream += OnNewStream;
                _agoraService.StartSession(Room, Consts.AgoraAPI, Consts.Token, webSdkInteroperability: true);
                _agoraService.ToggleCamera();
            }
        }
```

Console output for StartSession only (4G) - not working

> [Settings] Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> [SensorManager] registerListener :: 6, LSM6DSL Acceleration Sensor, 66667, 0,  
> [AudioManager] setSpeakerphoneOn false
> [AudioManager] setSpeakerphoneOn true
> Thread started:  #13
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> [*WEBRTCN*] SetRenderAndroidVM
> 

Console output for StartSession only (WI-FI) - working

> [Settings] Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> [SensorManager] registerListener :: 6, LSM6DSL Acceleration Sensor, 66667, 0,  
> [AudioManager] setSpeakerphoneOn false
> [AudioManager] setSpeakerphoneOn true
> Thread started:  #15
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> [*WEBRTCN*] SetRenderAndroidVM
> [] PlayerBase::PlayerBase()
> [] TrackPlayerBase::TrackPlayerBase()
> [libOpenSLES] Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
> [AudioTrack] AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 1600
> [AudioTrack] Need throttle time for OpenSLES player
> [libOpenSLES] Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
> [libOpenSLES] Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
> [AudioRecord] openRecord_l() remove fast or raw flag of voip calls, source=7, flags=5
> [Camera_APM :] [APM]APM's Thread is started
> [Camera_APM :] [APM] This app is forground app
> [] TrackPlayerBase::~TrackPlayerBase()
> [] PlayerBase::~PlayerBase()

First run full output 

> [Mono] Requesting loading reference 2 (of 4) of /storage/emulated/0/Android/data/gr.candi.csii/files/.__override__/Xamarin.Agora.Full.Android.dll
> [Mono] Loading reference 2 of /storage/emulated/0/Android/data/gr.candi.csii/files/.__override__/Xamarin.Agora.Full.Android.dll asmctx DEFAULT, looking for Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
> [Mono] Assembly Ref addref Xamarin.Agora.Full.Android[0x76df3d6b80] -> Java.Interop[0x76f094e700]: 11
> [Settings] Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> Thread started:  #9
> [SensorManager] registerListener :: 6, LSM6DSL Acceleration Sensor, 66667, 0,  
> [BluetoothAdapter] Application does not have bluetooth permission, registering is failed
> [BluetoothAdapter] 
> [BluetoothAdapter] java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10397 nor current process has android.permission.BLUETOOTH.
> [BluetoothAdapter] 	at android.os.Parcel.createException(Parcel.java:1966)
> [BluetoothAdapter] 	at android.os.Parcel.readException(Parcel.java:1934)
> [BluetoothAdapter] 	at android.os.Parcel.readException(Parcel.java:1884)
> [BluetoothAdapter] 	at android.bluetooth.IBluetoothManager$Stub$Proxy.registerStateChangeCallback(IBluetoothManager.java:478)
> [BluetoothAdapter] 	at android.bluetooth.BluetoothAdapter.<init>(BluetoothAdapter.java:789)
> [BluetoothAdapter] 	at android.bluetooth.BluetoothAdapter.getDefaultAdapter(BluetoothAdapter.java:770)
> [BluetoothAdapter] 	at io.agora.rtc.internal.AudioRoutingController.queryCurrentAudioRouting(AudioRoutingController.java:1174)
> [BluetoothAdapter] 	at io.agora.rtc.internal.AudioRoutingController.resetAudioRouting(AudioRoutingController.java:1116)
> [BluetoothAdapter] 	at io.agora.rtc.internal.AudioRoutingController.access$800(AudioRoutingController.java:29)
> [BluetoothAdapter] 	at io.agora.rtc.internal.AudioRoutingController$ControllerStartState.<init>(AudioRoutingController.java:462)
> [BluetoothAdapter] 	at io.agora.rtc.internal.AudioRoutingController.changeState(AudioRoutingController.java:312)
> [BluetoothAdapter] 	at io.agora.rtc.internal.AudioRoutingController.access$700(AudioRoutingController.java:29)
> [BluetoothAdapter] 	at io.agora.rtc.internal.AudioRoutingController$ControllerBaseState.setState(AudioRoutingController.java:336)
> [BluetoothAdapter] 	at io.agora.rtc.internal.AudioRoutingController.startMonitoring(AudioRoutingController.java:801)
> [BluetoothAdapter] 	at io.agora.rtc.internal.RtcEngineImpl.nativeJoinChannel(Native Method)
> [BluetoothAdapter] 	at io.agora.rtc.internal.RtcEngineImpl.joinChannel(RtcEngineImpl.java:528)
> [BluetoothAdapter] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
> [BluetoothAdapter] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
> [BluetoothAdapter] 	at android.os.Handler.handleCallback(Handler.java:873)
> [BluetoothAdapter] 	at android.os.Handler.dispatchMessage(Handler.java:99)
> [BluetoothAdapter] 	at android.os.Looper.loop(Looper.java:214)
> [BluetoothAdapter] 	at android.app.ActivityThread.main(ActivityThread.java:7045)
> [BluetoothAdapter] 	at java.lang.reflect.Method.invoke(Native Method)
> [BluetoothAdapter] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> [BluetoothAdapter] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
> [AudioManager] setSpeakerphoneOn false
> [AudioManager] setSpeakerphoneOn true
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> [*WEBRTCN*] SetRenderAndroidVM
> [AudioCapabilities] Unsupported mime audio/ac4
> [AudioCapabilities] Unsupported mime audio/x-ima
> [AudioCapabilities] Unsupported mime audio/eac3-joc
> [AudioCapabilities] Unsupported mime audio/evrc
> [AudioCapabilities] Unsupported mime audio/mpeg-L1
> [AudioCapabilities] Unsupported mime audio/mpeg-L2
> [Mono] Requesting loading reference 6 (of 8) of /storage/emulated/0/Android/data/gr.candi.csii/files/.__override__/Xamarin.Agora.Full.Forms.Droid.dll
> [Mono] Loading reference 6 of /storage/emulated/0/Android/data/gr.candi.csii/files/.__override__/Xamarin.Agora.Full.Forms.Droid.dll asmctx DEFAULT, looking for System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
> [Mono] Assembly Ref addref Xamarin.Agora.Full.Forms.Droid[0x76df3d6d80] -> System[0x76ee94e680]: 12
> [Mono] Requesting loading reference 5 (of 8) of /storage/emulated/0/Android/data/gr.candi.csii/files/.__override__/Xamarin.Agora.Full.Forms.Droid.dll
> [Mono] Loading reference 5 of /storage/emulated/0/Android/data/gr.candi.csii/files/.__override__/Xamarin.Agora.Full.Forms.Droid.dll asmctx DEFAULT, looking for Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
> [Mono] Assembly Ref addref Xamarin.Agora.Full.Forms.Droid[0x76df3d6d80] -> Xamarin.Forms.Core[0x76f094e100]: 10
> [AudioCapabilities] Unsupported mime audio/qcelp
> [AudioCapabilities] Unsupported mime audio/x-ms-wma
> [gr.candi.csii] JNI RegisterNativeMethods: attempt to register 0 native methods for crc643f46942d9dd1fff9.ViewRenderer
> [gr.candi.csii] JNI RegisterNativeMethods: attempt to register 0 native methods for crc64120e861055445a72.AgoraVideoViewRenderer
> [AudioCapabilities] Unsupported mime audio/evrc
> [AudioCapabilities] Unsupported mime audio/qcelp
> [VideoCapabilities] Unrecognized profile 4 for video/hevc
> [VideoCapabilities] Unsupported mime video/mp43
> [VideoCapabilities] Unrecognized profile/level 1/32 for video/mp4v-es
> [VideoCapabilities] Unrecognized profile/level 32768/2 for video/mp4v-es
> [VideoCapabilities] Unrecognized profile/level 32768/64 for video/mp4v-es
> [VideoCapabilities] Unsupported mime video/wvc1
> [VideoCapabilities] Unsupported mime video/wvc1
> [VideoCapabilities] Unsupported mime video/x-ms-wmv7
> [VideoCapabilities] Unsupported mime video/x-ms-wmv8
> [VideoCapabilities] Unsupported profile 4 for video/mp4v-es
> [Choreographer] Skipped 358 frames!  The application may be doing too much work on its main thread.
> [ViewRootImpl] sendUserActionEvent() returned.
> [ViewRootImpl@cb406a[MainActivity]] MSG_WINDOW_FOCUS_CHANGED 1 1
> [InputMethodManager] prepareNavigationBarInfo() DecorView@7915f50[MainActivity]
> [InputMethodManager] getNavigationBarColor() -855310
> [InputMethodManager] prepareNavigationBarInfo() DecorView@7915f50[MainActivity]
> [InputMethodManager] getNavigationBarColor() -855310
> [InputMethodManager] Starting input: tba=gr.candi.csii ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
> [InputMethodManager] startInputInner - Id : 0
> [InputMethodManager] startInputInner - mService.startInputOrWindowGainedFocus
> [InputTransport] Input channel constructed: fd=99
> [InputTransport] Input channel destroyed: fd=80
> [OpenGLRenderer] Davey! duration=6043ms; Flags=0, IntendedVsync=451063209913771, Vsync=451069176580199, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=451069192194624, AnimationStart=451069192289470, PerformTraversalsStart=451069193340893, DrawStart=451069229540239, SyncQueued=451069235061009, SyncStart=451069235197739, IssueDrawCommandsStart=451069235392124, SwapBuffers=451069251667470, FrameCompleted=451069253188393, DequeueBufferDuration=5016000, QueueBufferDuration=314000, 
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> [gr.candi.csii] Accessing hidden method Landroid/telephony/SignalStrength;->getDbm()I (light greylist, reflection)
> [gr.candi.csii] Accessing hidden method Landroid/telephony/SignalStrength;->getAsuLevel()I (light greylist, reflection)
> [Mono] Requesting loading reference 7 (of 8) of /storage/emulated/0/Android/data/gr.candi.csii/files/.__override__/Xamarin.Agora.Full.Forms.Droid.dll
> [Mono] Loading reference 7 of /storage/emulated/0/Android/data/gr.candi.csii/files/.__override__/Xamarin.Agora.Full.Forms.Droid.dll asmctx DEFAULT, looking for System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
> [Mono] Assembly Ref addref Xamarin.Agora.Full.Forms.Droid[0x76df3d6d80] -> System.Core[0x76f094ef80]: 12
> [SurfaceView] onWindowVisibilityChanged(0) true io.agora.rtc.video.ViEAndroidGLES20{2215355 V.E...... ......I. 0,0-0,0} of ViewRootImpl@cb406a[MainActivity]
> [*WEBRTCN*] StartRender: thread started: 3061839088
> [ViewRootImpl@cb406a[MainActivity]] Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 510446006272} changed=false
> [SurfaceView] show() Surface(name=SurfaceView - gr.candi.csii/crc6459ee78b1528a1457.MainActivity@2215355@0[31406])/@0x572665b io.agora.rtc.video.ViEAndroidGLES20{2215355 V.E...... ......ID 0,0-1080,1082}
> [SurfaceView] surfaceCreated 1 #8 io.agora.rtc.video.ViEAndroidGLES20{2215355 V.E...... ......ID 0,0-1080,1082}
> [SurfaceView] surfaceChanged (1080,1082) 1 #8 io.agora.rtc.video.ViEAndroidGLES20{2215355 V.E...... ......ID 0,0-1080,1082}
> [mali_winsys] EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
> [AGORA_SDK] Surface changed to width 1080 height 1082

Second run full output

> [Settings] Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> [SensorManager] registerListener :: 6, LSM6DSL Acceleration Sensor, 66667, 0,  
> [AudioManager] setSpeakerphoneOn false
> [AudioManager] setSpeakerphoneOn true
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> Thread started:  #12
> [*WEBRTCN*] SetRenderAndroidVM
> [Choreographer] Skipped 253 frames!  The application may be doing too much work on its main thread.
> [ViewRootImpl@cb406a[MainActivity]] MSG_WINDOW_FOCUS_CHANGED 1 1
> [InputMethodManager] prepareNavigationBarInfo() DecorView@7915f50[MainActivity]
> [InputMethodManager] getNavigationBarColor() -855310
> [InputMethodManager] prepareNavigationBarInfo() DecorView@7915f50[MainActivity]
> [InputMethodManager] getNavigationBarColor() -855310
> [InputMethodManager] Starting input: tba=gr.candi.csii ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
> [InputMethodManager] startInputInner - Id : 0
> [InputMethodManager] startInputInner - mService.startInputOrWindowGainedFocus
> [OpenGLRenderer] Davey! duration=4263ms; Flags=0, IntendedVsync=451393603176614, Vsync=451397819843112, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=451397834199697, AnimationStart=451397834255350, PerformTraversalsStart=451397834895120, DrawStart=451397856499004, SyncQueued=451397860408312, SyncStart=451397860557697, IssueDrawCommandsStart=451397860761735, SwapBuffers=451397865229697, FrameCompleted=451397867273389, DequeueBufferDuration=556000, QueueBufferDuration=768000, 
> [InputTransport] Input channel constructed: fd=108
> [InputTransport] Input channel destroyed: fd=84
> [ViewRootImpl] sendUserActionEvent() returned.
> [libc] Access denied finding property "net.dns1"
> [libc] Access denied finding property "net.dns2"
> [libc] Access denied finding property "net.dns3"
> [libc] Access denied finding property "net.dns4"
> [SurfaceView] onWindowVisibilityChanged(0) true io.agora.rtc.video.ViEAndroidGLES20{d2efd6a V.E...... ......I. 0,0-0,0} of ViewRootImpl@cb406a[MainActivity]
> [ViewRootImpl@cb406a[MainActivity]] Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 510393630720} changed=false
> [*WEBRTCN*] StartRender: thread started: 3113678064
> [SurfaceView] show() Surface(name=SurfaceView - gr.candi.csii/crc6459ee78b1528a1457.MainActivity@d2efd6a@0[31406])/@0x1a7caf8 io.agora.rtc.video.ViEAndroidGLES20{d2efd6a V.E...... ......ID 0,0-1080,1082}
> [SurfaceView] surfaceCreated 1 #8 io.agora.rtc.video.ViEAndroidGLES20{d2efd6a V.E...... ......ID 0,0-1080,1082}
> [SurfaceView] surfaceChanged (1080,1082) 1 #8 io.agora.rtc.video.ViEAndroidGLES20{d2efd6a V.E...... ......ID 0,0-1080,1082}
> [mali_winsys] EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
> [AGORA_SDK] Surface changed to width 1080 height 1082

**Comment by georgemichailou** [comment]
Is it necessary to add a Xamarin.Agora.Full.Android if i use Xamarin.Agora.Full.Forms on xamarin forms android project ?

**Comment by georgemichailou** [comment]
I check also and this link for Black screen on the local side

https://docs.agora.io/en/faq/video_blank?_ga=2.33075710.1173214553.1588850522-534750499.1584045881#issue-description

**Comment by georgemichailou** [comment]
Maybe the network connection is poor. I close this issue.
